# Generated by Django 4.2.18 on 2025-01-29 19:45

from django.db import migrations, models
import django.db.models.deletion
import stores.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetName', models.TextField(default='')),
                ('streetNumber', models.TextField(default='')),
                ('city', models.TextField(default='')),
                ('state', models.TextField(default='')),
                ('zipCode', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.IntegerField(default=0)),
                ('longitude', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('imageUrl', models.TextField()),
                ('contactPhone', models.TextField()),
                ('address', models.OneToOneField(default=stores.models.default_address, on_delete=django.db.models.deletion.CASCADE, to='stores.address')),
                ('location', models.OneToOneField(default=stores.models.default_location, on_delete=django.db.models.deletion.CASCADE, to='stores.location')),
            ],
        ),
    ]
