# Generated by Django 4.2.18 on 2025-02-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='contactPhone',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='store',
            name='imageUrl',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
