# Generated by Django 4.2.18 on 2025-02-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('imageUrl', models.TextField()),
                ('price', models.IntegerField()),
                ('currency', models.TextField(choices=[('€', '€'), ('$', '$'), ('£', '£')])),
                ('category', models.TextField(choices=[('Accessories', 'Accessories'), ('Fitness', 'Fitness'), ('Electronics', 'Electronics'), ('Clothing', 'Clothing')])),
                ('inventoryStatus', models.TextField(choices=[('INSTOCK', 'INSTOCK'), ('LOWSTOCK', 'LOWSTOCK'), ('OUTOFSTOCK', 'OUTOFSTOCK')])),
            ],
        ),
    ]
