# Generated by Django 4.2.18 on 2025-02-12 02:45

from django.db import migrations, models
import django.db.models.deletion
import stores.models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_store_contactphone_alter_store_imageurl_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default=stores.models.default_store, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
    ]
